Repository ezzop/HacktoberFest2022, pull requests merged in 2022-10, with the labels that each got.

#3 ADD: Dice App Web Development Application
  Web Development/Dice App/.DS_Store
  Web Development/Dice App/dicee.html
  Web Development/Dice App/images/dice1.png
  Web Development/Dice App/images/dice2.png
  Web Development/Dice App/images/dice3.png
  Web Development/Dice App/images/dice4.png
  Web Development/Dice App/images/dice5.png
  Web Development/Dice App/images/dice6.png
  Web Development/Dice App/index.js
  Web Development/Dice App/styles.css
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest22

#4 Add: Instagram API Clone using Go Language
  Go/Instagram API Clone/go.mod
  Go/Instagram API Clone/go.sum
  Go/Instagram API Clone/instagram.go
  Go/Instagram API Clone/readme.md
  Go/Instagram API Clone/testing.txt
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest22

#5 Create resume-scanner.py
  Python/resume-scanner.py
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest22

#6 Update README.md
  README.md
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest22

#10 added post_api to api folder
  API/POST_API/.gitignore
  API/POST_API/README.md
  API/POST_API/app.js
  API/POST_API/package-lock.json
  API/POST_API/package.json
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest22

#12 Revert "Json_Parse"
  API/json_parse/README.md
  API/json_parse/app.php
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest22

#13 added web crawler
  API/Web-crawler/.gitignore
  API/Web-crawler/README.md
  API/Web-crawler/data.csv
  API/Web-crawler/package-lock.json
  API/Web-crawler/package.json
  API/Web-crawler/src/app.js
  API/Web-crawler/src/crawldata.js
  API/Web-crawler/src/createcsvfile.js
  API/Web-crawler/src/data.csv
  API/Web-crawler/src/dbconnect.js
  API/Web-crawler/src/dbwrite.js
  API/Web-crawler/src/writecsv.js
  API/json_parse/README.md
  API/json_parse/app.php
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest22

#23 ADD: Simon Game
  Web Development/Simon Game/game.js
  Web Development/Simon Game/index.html
  Web Development/Simon Game/sounds/blue.mp3
  Web Development/Simon Game/sounds/green.mp3
  Web Development/Simon Game/sounds/red.mp3
  Web Development/Simon Game/sounds/wrong.mp3
  Web Development/Simon Game/sounds/yellow.mp3
  Web Development/Simon Game/styles.css
Labels: enhancement, good first issue, hacktoberfest, hacktoberfest-accepted, hacktoberfest22

#24 ADD: Portfolio app
  Web Development/Portfolio/StubCode.html
  Web Development/Portfolio/css/styles.css
  Web Development/Portfolio/images/AyanCircle.png
  Web Development/Portfolio/images/alien.gif
  Web Development/Portfolio/images/chillies.png
  Web Development/Portfolio/images/cloud.png
  Web Development/Portfolio/images/coding.png
  Web Development/Portfolio/images/computer.png
  Web Development/Portfolio/images/favicon.ico
  Web Development/Portfolio/images/mountain.png
  Web Development/Portfolio/index.html
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest22

#26 ADD: Jquery Practice
  Web Development/Jquery App/index.html
  Web Development/Jquery App/index.js
  Web Development/Jquery App/styles.css
Labels: enhancement, good first issue, hacktoberfest, hacktoberfest-accepted, hacktoberfest22

#28 added todo_board api
  API/todo_board/.gitignore
  API/todo_board/README.md
  API/todo_board/babel.config.js
  API/todo_board/deploy.sh
  API/todo_board/dist/css/chunk-vendors.8bda0bd5.css
  API/todo_board/dist/favicon.ico
  API/todo_board/dist/index.html
  API/todo_board/dist/js/app.a6ee7df6.js
  API/todo_board/dist/js/app.a6ee7df6.js.map
  API/todo_board/dist/js/chunk-vendors.32334c56.js
  API/todo_board/dist/js/chunk-vendors.32334c56.js.map
  API/todo_board/package-lock.json
  API/todo_board/package.json
  API/todo_board/public/favicon.ico
  API/todo_board/public/index.html
  API/todo_board/src/App.vue
  API/todo_board/src/components/HelloWorld.vue
  API/todo_board/src/main.js
Labels: good first issue, hacktoberfest, hacktoberfest-accepted, hacktoberfest22

#29 Temperature Convertor
  Web Development/temp_convertor/index.css
  Web Development/temp_convertor/index.html
  Web Development/temp_convertor/script.js
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest22

#32 Added Some new python codes.
  Python/Random_password_generator.py
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest22

#34 Added helmet.py
  Artificial Intelligence/helmet.py
  Python/TaxiBooking.py
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest22

#35 drum play added in Web development
  Web Development/Drum Kit play/.DS_Store
  Web Development/Drum Kit play/images/crash.png
  Web Development/Drum Kit play/images/kick.png
  Web Development/Drum Kit play/images/snare.png
  Web Development/Drum Kit play/images/tom1.png
  Web Development/Drum Kit play/images/tom2.png
  Web Development/Drum Kit play/images/tom3.png
  Web Development/Drum Kit play/images/tom4.png
  Web Development/Drum Kit play/index.html
  Web Development/Drum Kit play/index.js
  Web Development/Drum Kit play/sounds/crash.mp3
  Web Development/Drum Kit play/sounds/kick-bass.mp3
  Web Development/Drum Kit play/sounds/snare.mp3
  Web Development/Drum Kit play/sounds/tom-1.mp3
  Web Development/Drum Kit play/sounds/tom-2.mp3
  Web Development/Drum Kit play/sounds/tom-3.mp3
  Web Development/Drum Kit play/sounds/tom-4.mp3
  Web Development/Drum Kit play/styles.css
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest22

#38 Added Tictactoe game
  Python/tictactoe.py
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest22

#53 Added Marathon Time Prediction
  Machine Learning/Marathon Time Prediction/Dataset/MarathonData.csv
  Machine Learning/Marathon Time Prediction/Dataset/README.md
  Machine Learning/Marathon Time Prediction/Model/.ipynb_checkpoints/marathon_time_prediction-checkpoint.ipynb
  Machine Learning/Marathon Time Prediction/Model/README.md
  Machine Learning/Marathon Time Prediction/Model/marathon_time_prediction.ipynb
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest22

#55 added basic expense tracket created using vanilla js
  Web Development/expense-tracker/index.html
  Web Development/expense-tracker/readme.md
  Web Development/expense-tracker/script.js
  Web Development/expense-tracker/style.css
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest22

#58 Added a python game
  Python/three musketeers.py
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest22

#60 Create StarPyramid.cpp
  C++/StarPyramid.cpp
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest22

#61 cafe landing page
  Web Development/Cafe Landing Page/images/1111.PNG
  Web Development/Cafe Landing Page/images/222222.PNG
  Web Development/Cafe Landing Page/images/cake1.PNG
  Web Development/Cafe Landing Page/images/cake2.PNG
  Web Development/Cafe Landing Page/images/deck1.PNG
  Web Development/Cafe Landing Page/images/deck2.PNG
  Web Development/Cafe Landing Page/images/deck3.PNG
  Web Development/Cafe Landing Page/images/deck4.PNG
  Web Development/Cafe Landing Page/images/final1.PNG
  Web Development/Cafe Landing Page/images/final2.PNG
  Web Development/Cafe Landing Page/images/final3.PNG
  Web Development/Cafe Landing Page/images/final4.PNG
  Web Development/Cafe Landing Page/images/final5.PNG
  Web Development/Cafe Landing Page/images/final6.PNG
  Web Development/Cafe Landing Page/images/first.PNG
  Web Development/Cafe Landing Page/images/fuh.jfif
  Web Development/Cafe Landing Page/images/logo.PNG
  Web Development/Cafe Landing Page/images/logo1.PNG
  Web Development/Cafe Landing Page/images/maining.jfif
  Web Development/Cafe Landing Page/images/one.jfif
  Web Development/Cafe Landing Page/images/soon.PNG
  Web Development/Cafe Landing Page/images/yoo.PNG
  Web Development/Cafe Landing Page/index.html
  Web Development/Cafe Landing Page/style.css
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest22

#64 Git-Automation-Script
  github.sh/README.md
  github.sh/github.sh
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest22
